# Generated by Django 4.1.1 on 2023-10-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUserPermissions',
        ),
    ]
