# Generated by Django 4.1.1 on 2022-10-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_alter_fornecedor_documento_alter_fornecedor_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conta',
            options={'managed': False, 'verbose_name_plural': 'Conta'},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'managed': False, 'verbose_name_plural': 'Fornecedor'},
        ),
    ]
