# Generated by Django 4.1.1 on 2022-10-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0005_bairros_cidades_dimcontas_dimgrupocontas_empresas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairros',
            options={'managed': False, 'verbose_name_plural': 'Bairros'},
        ),
        migrations.AlterModelOptions(
            name='cidades',
            options={'managed': False, 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='conta',
            options={'managed': False, 'verbose_name_plural': 'Contas'},
        ),
        migrations.AlterModelOptions(
            name='dimcontas',
            options={'managed': False, 'verbose_name_plural': 'Dimcontas'},
        ),
        migrations.AlterModelOptions(
            name='dimgrupocontas',
            options={'managed': False, 'verbose_name_plural': 'Dimgrupocontas'},
        ),
        migrations.AlterModelOptions(
            name='empresas',
            options={'managed': False, 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='estados',
            options={'managed': False, 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'managed': False, 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='matrizcontafornecedor',
            options={'managed': False, 'verbose_name_plural': 'Matriz Conta Fornecedor'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'managed': False, 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='projetos',
            options={'managed': False, 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AlterModelOptions(
            name='regioes',
            options={'managed': False, 'verbose_name_plural': 'Regioes'},
        ),
    ]
