# Generated by Django 4.1.1 on 2022-11-03 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0007_teste1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teste1',
        ),
    ]
