# Generated by Django 4.1.1 on 2023-10-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fincontaanalitica',
            options={'managed': False, 'verbose_name_plural': 'PC - Analitico'},
        ),
        migrations.AlterModelOptions(
            name='fingrupocontas',
            options={'managed': False, 'verbose_name_plural': 'PC - Grupo de Contas'},
        ),
        migrations.AlterModelOptions(
            name='finsubgrupocontas',
            options={'managed': False, 'verbose_name_plural': 'PC - SubGrupoContas'},
        ),
        migrations.AlterModelOptions(
            name='matrizanaliticafornecedor',
            options={'managed': False, 'verbose_name_plural': 'Vinculo Conta-Fornecedor'},
        ),
    ]
