# Generated by Django 4.1.1 on 2022-12-22 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairros',
            fields=[
                ('id_bairro', models.AutoField(primary_key=True, serialize=False)),
                ('cod_bairro', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Bairros',
                'db_table': 'bairros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('cod_cidade', models.AutoField(primary_key=True, serialize=False)),
                ('cod_ibge', models.IntegerField()),
                ('cidade', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Cidades',
                'db_table': 'cidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dimcontas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_conta', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualiza', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dimcontas',
                'db_table': 'dimcontas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dimgrupocontas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_grupo_conta', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dimgrupocontas',
                'db_table': 'dimgrupocontas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('cod_empresa', models.BigAutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualiza', models.DateTimeField(auto_now=True)),
                ('safegold_ger', models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], default=1, null=True, verbose_name='Safegold Gerência? ')),
                ('cnpj', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['-cod_empresa'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('cod_estado', models.IntegerField()),
                ('cod_uf', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinGrupoContas',
            fields=[
                ('cod_grupo_contas', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_grupo_contas', models.CharField(blank=True, max_length=300, null=True)),
                ('permite_vinculo', models.CharField(blank=True, max_length=3, null=True)),
                ('sumario', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Grupo de Contas // Plano de Contas',
                'db_table': 'fin_grupo_contas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinPlanoContas',
            fields=[
                ('cod_plano_conta', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_conta', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Analitico // Plano de Contas',
                'db_table': 'fin_plano_contas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinSubgrupoContas',
            fields=[
                ('cod_subgrupo_contas', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_subgrupo_contas', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'SubgrupoContas // Plano de Contas',
                'db_table': 'fin_subgrupo_contas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MatrizContaFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_fornecedor', models.BigIntegerField()),
                ('desc_fornecedor', models.CharField(max_length=255)),
                ('data_importacao', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Matriz Conta Fornecedor',
                'db_table': 'matriz_conta_fornecedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('cod_pais', models.BigAutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(blank=True, max_length=60, null=True)),
                ('pais_pt', models.CharField(blank=True, max_length=60, null=True)),
                ('sigla', models.CharField(blank=True, max_length=2, null=True)),
                ('bacen', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('cod_projeto', models.BigAutoField(primary_key=True, serialize=False)),
                ('projeto', models.CharField(blank=True, max_length=255, null=True)),
                ('chave_integracao', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_usuario', models.IntegerField(blank=True, null=True)),
                ('chave_inteligente', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_segmento', models.IntegerField(blank=True, null=True)),
                ('ativo', models.IntegerField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_nome_arq', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_tamanho', models.BigIntegerField(blank=True, null=True)),
                ('avatar_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('tipo_endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('end_numero', models.CharField(blank=True, max_length=255, null=True)),
                ('end_compl', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=255, null=True)),
                ('data_fecha', models.DateField(blank=True, null=True)),
                ('id_importacao', models.IntegerField(blank=True, null=True)),
                ('end_cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('resp_email', models.CharField(blank=True, max_length=255, null=True)),
                ('resp_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('resp_cod', models.CharField(blank=True, max_length=255, null=True)),
                ('job_state', models.CharField(blank=True, max_length=255, null=True)),
                ('job_report', models.TextField(blank=True, null=True)),
                ('job_id', models.IntegerField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField()),
                ('data_atualiza', models.DateTimeField()),
                ('legacy_id', models.IntegerField(blank=True, null=True)),
                ('safegold_ger', models.IntegerField(blank=True, null=True)),
                ('cod_sub_segmento', models.IntegerField(blank=True, null=True)),
                ('sandbox', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Projetos',
                'db_table': 'projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regioes',
            fields=[
                ('cod_regiao', models.AutoField(primary_key=True, serialize=False)),
                ('regiao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Regioes',
                'db_table': 'regioes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projetos_teste',
            fields=[
                ('cod_projeto1', models.BigAutoField(primary_key=True, serialize=False)),
                ('projeto1', models.CharField(blank=True, max_length=255, null=True)),
                ('chave_integracao1', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_usuario1', models.IntegerField(blank=True, null=True)),
                ('chave_inteligente1', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_segmento1', models.IntegerField(blank=True, null=True)),
                ('ativo1', models.IntegerField(blank=True, null=True)),
                ('cor1', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_nome_arq1', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_tipo1', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_tamanho1', models.BigIntegerField(blank=True, null=True)),
                ('avatar_atualizacao1', models.DateTimeField(blank=True, null=True)),
                ('tipo_endereco1', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco1', models.CharField(blank=True, max_length=255, null=True)),
                ('end_numero1', models.CharField(blank=True, max_length=255, null=True)),
                ('end_compl', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro1', models.CharField(blank=True, max_length=255, null=True)),
                ('cep1', models.CharField(blank=True, max_length=255, null=True)),
                ('data_fecha1', models.DateField(blank=True, null=True)),
                ('id_importacao1', models.IntegerField(blank=True, null=True)),
                ('end_cidade1', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade1', models.CharField(blank=True, max_length=255, null=True)),
                ('resp_email1', models.CharField(blank=True, max_length=255, null=True)),
                ('resp_nome1', models.CharField(blank=True, max_length=255, null=True)),
                ('resp_cod1', models.CharField(blank=True, max_length=255, null=True)),
                ('job_state1', models.CharField(blank=True, max_length=255, null=True)),
                ('job_report1', models.TextField(blank=True, null=True)),
                ('job_id1', models.IntegerField(blank=True, null=True)),
                ('data_criacao1', models.DateTimeField()),
                ('data_atualiza1', models.DateTimeField()),
                ('legacy_id1', models.IntegerField(blank=True, null=True)),
                ('safegold_ger1', models.IntegerField(blank=True, null=True)),
                ('cod_sub_segmento1', models.IntegerField(blank=True, null=True)),
                ('sandbox1', models.IntegerField(blank=True, null=True)),
                ('end_estado1', models.ForeignKey(blank=True, db_column='end_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud_app.estados')),
            ],
            options={
                'verbose_name_plural': 'Projetos_teste',
                'db_table': 'projetos_teste',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User_projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_projeto', models.ManyToManyField(to='crud_app.projetos_teste')),
                ('id_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_projeto',
                'managed': True,
            },
        ),
    ]
