# Generated by Django 4.1.1 on 2023-02-07 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='id_user',
            field=models.ManyToManyField(through='crud_app.projeto_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
