# Generated by Django 4.1.1 on 2023-02-07 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud_app', '0002_alter_projetos_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'projeto_user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='projeto_user',
        ),
        migrations.AlterField(
            model_name='projetos',
            name='id_user',
            field=models.ManyToManyField(through='crud_app.ProjetoUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
