# Generated by Django 4.1.1 on 2023-02-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_projetouser_delete_projeto_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinContaAnalitica',
            fields=[
                ('cod_conta_analitica', models.AutoField(primary_key=True, serialize=False)),
                ('desc_conta', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Analitico // Plano de Contas',
                'db_table': 'fin_conta_analitica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('cod_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('insc_est', models.CharField(blank=True, max_length=20, null=True)),
                ('matriz', models.CharField(blank=True, max_length=3, null=True)),
                ('cod_fornec', models.IntegerField(blank=True, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fornecedor',
                'db_table': 'fornecedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MatrizAnaliticaFornecedor',
            fields=[
                ('cod_matriz_analitica_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('vinculo', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vinculo de Fornecedor á Conta Analitica',
                'db_table': 'matriz_analitica_fornecedor',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FinPlanoContas',
        ),
        migrations.DeleteModel(
            name='MatrizContaFornecedor',
        ),
    ]
