# Generated by Django 4.1.1 on 2023-03-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_fincontaanalitica_fornecedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('financeiro', models.IntegerField(blank=True, null=True)),
                ('avaliacao', models.IntegerField(blank=True, null=True)),
                ('is_head', models.IntegerField(blank=True, null=True)),
                ('idrh_cargo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RhCargo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_cargo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rh_cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RhClassificacaoComp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('classificacao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'rh_classificacao_comp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RhFactCargoMetas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idrh_cargo', models.IntegerField(blank=True, null=True)),
                ('idrh_fact_comportamental', models.IntegerField(blank=True, null=True)),
                ('valor_ncf', models.FloatField(blank=True, null=True)),
                ('idrh_classificacao_comp', models.IntegerField(blank=True, null=True)),
                ('qtde_indicadores', models.IntegerField(blank=True, null=True)),
                ('peso_indicadores', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rh_fact_cargo_metas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RhFactComportamental',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('indicador', models.CharField(blank=True, max_length=255, null=True)),
                ('competencia', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'rh_fact_comportamental',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RhMapCargoComp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idrh_cargo', models.IntegerField(blank=True, null=True)),
                ('idrh_fact_comportamental', models.IntegerField(blank=True, null=True)),
                ('idrh_classificacao_comp', models.IntegerField(blank=True, null=True)),
                ('instrucoes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rh_map_cargo_comp',
                'managed': False,
            },
        ),
    ]
