# Generated by Django 4.1.1 on 2022-12-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0009_auto_20221104_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinGrupoContas',
            fields=[
                ('cod_grupo_contas', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_grupo_contas', models.CharField(blank=True, max_length=300, null=True)),
                ('permite_vinculo', models.CharField(blank=True, max_length=3, null=True)),
                ('sumario', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fin_grupo_contas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinPlanoContas',
            fields=[
                ('cod_plano_conta', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_conta', models.CharField(blank=True, max_length=300, null=True)),
                ('cod_subgrupo_contas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fin_plano_contas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinSubgrupoContas',
            fields=[
                ('cod_subgrupo_contas', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_subgrupo_contas', models.CharField(blank=True, max_length=300, null=True)),
                ('cod_grupo_contas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fin_subgrupo_contas',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='empresas',
            options={'managed': False, 'ordering': ['-cod_empresa'], 'verbose_name_plural': 'Empresas'},
        ),
    ]
