# Generated by Django 4.1.1 on 2022-12-16 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud_app', '0010_fingrupocontas_finplanocontas_finsubgrupocontas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fingrupocontas',
            options={'managed': False, 'verbose_name_plural': 'Grupo de Contas // Plano de Contas'},
        ),
        migrations.AlterModelOptions(
            name='finplanocontas',
            options={'managed': False, 'verbose_name_plural': 'Analitico // Plano de Contas'},
        ),
        migrations.AlterModelOptions(
            name='finsubgrupocontas',
            options={'managed': False, 'verbose_name_plural': 'SubgrupoContas // Plano de Contas'},
        ),
        migrations.CreateModel(
            name='User_projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('user_projeto', models.ManyToManyField(to='crud_app.projetos')),
            ],
        ),
    ]
