# Generated by Django 4.1.1 on 2022-12-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0011_alter_fingrupocontas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_projeto',
            options={'managed': False, 'verbose_name_plural': 'User_projetos'},
        ),
    ]
