# Generated by Django 4.1.1 on 2022-12-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0012_alter_user_projeto_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_projeto',
            table='User_projetos',
        ),
    ]
