# Generated by Django 4.1.1 on 2023-07-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgFactAgenda',
            fields=[
                ('cod_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, null=True)),
                ('dia_semana', models.CharField(blank=True, max_length=255, null=True)),
                ('atendimento', models.CharField(blank=True, max_length=255, null=True)),
                ('horas', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ag_fact_agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgTipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ag_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('cod_empresa', models.BigAutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualiza', models.DateTimeField(auto_now=True)),
                ('safegold_ger', models.IntegerField(blank=True, choices=[(0, 'Não'), (1, 'Sim')], default=1, null=True, verbose_name='Safegold Gerência? ')),
                ('cnpj', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['-cod_empresa'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('cod_projeto', models.BigAutoField(primary_key=True, serialize=False)),
                ('projeto', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_segmento', models.IntegerField(blank=True, null=True)),
                ('ativo', models.IntegerField(blank=True, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateTimeField()),
                ('data_atualiza', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Projetos',
                'db_table': 'projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'projeto_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgArea',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'sg_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgAvaliador',
            fields=[
                ('id_avaliador', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sg_avaliador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgAvaliadorGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sg_avaliador_gestor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgFuncao',
            fields=[
                ('id_funcao', models.AutoField(primary_key=True, serialize=False)),
                ('funcao', models.CharField(blank=True, max_length=40, null=True)),
                ('carga_horaria', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sg_funcao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgFuncaoGestor',
            fields=[
                ('id_func_gest', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sg_funcao_gestor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgUnidadeNegocio',
            fields=[
                ('id_unidade', models.AutoField(primary_key=True, serialize=False)),
                ('unidade', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sg_unidade_negocio',
                'managed': False,
            },
        ),
    ]
