# Generated by Django 4.1.1 on 2023-10-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_segmentoprojeto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgFactAgenda',
        ),
        migrations.DeleteModel(
            name='AgTipo',
        ),
        migrations.DeleteModel(
            name='SgArea',
        ),
        migrations.DeleteModel(
            name='SgAvaliador',
        ),
        migrations.DeleteModel(
            name='SgAvaliadorGestor',
        ),
        migrations.DeleteModel(
            name='SgFuncao',
        ),
        migrations.DeleteModel(
            name='SgFuncaoGestor',
        ),
        migrations.DeleteModel(
            name='SgUnidadeNegocio',
        ),
        migrations.AlterModelOptions(
            name='projetos',
            options={'managed': False, 'ordering': ['-ativo', 'projeto'], 'verbose_name_plural': 'Projetos'},
        ),
    ]
